import { Container, Row, Col } from 'react-bootstrap';
import {Link} from 'react-router-dom';
import '../../.././Style.css';
import TextToSpeech from '../../TextToSpeech';
function Book1Ch13Schillinger() {
  return (
    <div>
      <Container>
        <br /> 
        <h1>Schillinger Source Text for Book 1 Chapter 13</h1>
        <br />
        <TextToSpeech 
        text="
        CHAPTER 13. EVOLUTION OF RHYTHM STYLES (FAMILIES).
        WE MAY note that uniform groups, as well as non-uniform groups, generate various resultants. Whereas synchronized monomial periodicities generate symmetric polynomial resultants, distribution within any T (the determinant of a series) produces binomials or trinomials characteristic of all resultants where such T is a major generator.
        Taking all the possible binomials of a certain T and synchronizing them with their converses, trinomial resultants may be obtained. Through synchronizing all permutations of such trinomial resultants (of one series), quintinomials are obtained. The resultants of quintinomials and their permutation-groups produce groups with nine terms.
        This is a normal serial development as observed in various phenomena (for instance, in crystal formation).
        Formula.
        i sub n = 2 n t sub (n minus 1) minus 1.
        The number of terms in the nth interference-group equals the product of the number of terms in the n minus 1^st> interference-group by 2, minus 1.
        Example.
        The first interference-group i sub 1 = 2.
        The second interference-group i sub 2 = (2 times 2) minus 1 = 3.
        The third interference-group i sub 3 = (2 times 3) minus 1 = 5.
        The fourth interference-group i sub 4 = (2 times 5) minus 1 = 9.
        The fifth interference-group i sub 5 = (2 times 9) minus 1 =17.
        With the limit 9 as a determinant of a series, the maximum non-uniform resultants are quintinomials. Uniform resultants follow the maximum non-uniform resultants. The greater the number-value of a determinant, the more interference-groups it produces. While the determinant 3 produces only one non-uniform interference-group, 9 produces three non-uniform interference-groups.
        All the consecutive interference-groups generated by one determinant constitute the evolution of all rhythmic patterns in the corresponding family (style).
        This makes it possible to predict all future rhythmic patterns of one family as well as to trace the origin of more involved rhythms.
        As previously mentioned, the original (binomial) interference-groups may be obtained directly from a determinant. For example, the distribution of a determinant 5 gives 3 + 2 and 4 + 1, and their permutations. These binomials are the first and the last binomials of the resultants obtained from two uniform monomial generators in which the determinant of a series is a major generator (ae).
        Therefore, 3 + 2 are the first two terms of a resultant where ae = 5; 4 + 1 are the last two terms of a resultant where ae = 5.
        In order to trace the origin of a binomial with respect to two uniform generators, it is necessary to take the greater number-value of the binomial and to assign it as a minor generator (b). The sum of the binomial is the major generator.
        Example.
        Find the determinant of the series.
        5 + 3 = 8    
        The determinant is 8 8.
        Find the ae and b generators.
        b = 5
        ae = 5 + 3 = 8.
        The binomial represents the first two terms of r 8 5.
        Existing music often works on more than one determinant, thus producing various hybrids. It is very easy to trace the origin of any rhythmic hybrid, as such groups which are alien to the family are indicated in musical notation by the numbers. For instance, the triplets in 4 4 time; the duplets 3 4 time, etc. 
        Leaving theories aside for the moment, I believe that the actual cause of any new interference-binomial appearing in the world is the urge toward imbalancing, that is, the centrifugal tendency.
        In the light of such a hypothesis, the origin of the  Charleston 5 + 3 binomial may be explained as a tendency to disturb the balance of 2 4 + 2 4 in  4 4 or  4 8+ 4 8 in  8 8.
        Chronologically, the more unbalanced binomials (such as 7 8 + 1 8) appear later than the balanced ones (such as 5 8 + 3 8), regardless of their structural complexity. While 5 + 3 has been known in the American dance-music for some time, 1 + 7 appeared as a prominent pattern only with the song,  Organ Grinder’s Swing.
        The prediction of new rhythmic families to come is based on the principle of the growth- through-power series.
        So far we have had, during the entire range of recorded history, the evolution of 2 2 into its second power 4 4, and into its third power 8 8. Most probably 9 9 will take its place in the near future as the second power of 3 3; The series, 6 6 is an exhausted European hybrid, being the product of 2 X 3. The 5 5 and 7 7 series are Oriental series of old origin. They may become fashionable for a while in the Western musical world.
        Thus, the series of factorial-fractional continuity express the evolutionary forms in the two-coordinate system.
        A. SWING MUSIC.
        The following is an analysis of the phenomenon known as swing music; it is an analysis of  swing as it is performed, not as it is written out on paper. In view of the fact that triplets of eighths in common time are very prominent in this type of playing, particular attention must be given to the value 3, its multiples and its powers. Knowing from the previous analysis that 9 9 is the most probable candidate for the new style, I have studied all the  waltz-like phenomena which have appeared during the last few decades. The utmost plasticity of the Viennese type of waltz (such as the waltz from Rosenkavdlier by Richard Strauss) is due to this figure.
        The above is 3 + 1 + 5 + 1 + 5 + 1 + 2 etc., where the characteristic grouping is one appearing between the two fives.
        The trinomial 4 +1 + 4 can be found in the second interference group in the 9 9 series. Here again (as in the case of powers) is the intuitive approximation of the correct patterns. The waltz pattern is  trying to evolve into its second power. The idea of unity between the two greater number-values is right, but the number-values are only approximately correct.
        There are other hybrids which are characteristic of Viennese waltzes. For example, a hybrid between 3 3 and 4 4 series. 3 + 1 coming from 4 4 series and placed into 6 6 series ( 3 4 time).
        Most jazz ( Charleston Rhythm) 'is a hybrid between 8 8 and 6 6 series.
        Examine the following.
        And so, too, with all patterns of 6 6 series put into 8 8 time.
        The original binomial of this style is most characteristic of Viennese waltzes.
        Also the trinomial of 6 6 series. 1 + 1 + 4,
        See Rosenkavalier.
        This, being placed into 8 8 time, produces.
        An approach to the 9 9 family from another angle is swing.  The foundation of the latter is the foxtrot in triplets. Rhythms of 4 4 and 8 8 are modified on a basis of 12 12 or 12 8 and 4 4 (in triplets) musically.
        The common denominator units are the eighths.
        Through syncopation tendencies, plus the 3 3 series binomial, we obtain all the possible patterns of  swing.
        The original patterns.
        The syncopated patterns.
        The characteristic values are.
        2, i.e.  (an eighth tied to an eighth, or a quarter).
        3, i.e.  (a quarter tied to an eighth, or an eighth tied to a quarter).
        4, i.e.  (a quarter tied to a quarter).
        Often some of these number-values appear as rests.
        It is interesting to note that, even in bands such as Benny Goodman’s, all orchestral parts are written either in the 4 4 series patterns or 8 8 series patterns, but are then translated into  swing while being played. line 4, is the first true pattern of a 9 9 series trinomial (4 + 1 + 4). This pattern, with greater consistency, would appear as in line 4 ae. The number-values are correct but the group unit is wrong. It is applied in the wrong type of measure, 12 12 instead of 9 9.
        Thus, we can see that both the Viennese waltz and the fox-trot are engaged in a struggle for crystallization of the 9 9 family.
        All rhythmic interference groups have as the only alternatives in their evolution. either to evolve the higher powers of the same patterns, or to evolve into the higher powers of the same determinant.
        The entire process of the evolution of rhythmic families may be expressed as follows.
        r - is the resultant.
        P - Permutations.
        S - Synchronization.
        I - interference.
        Continuous dotted line represents uniformity.
        The first resultant (r sub 1) produces its permutations (P r sub 1) which form the first interference-group; these being synchronized (S P r sub 1) produce the first interference. The resultant of this interference is the second resultant (r sub 2), etc.
        The following graphs should be converted into musical notation.
        "
        />
        <br />
        <img className="img-fluid img-thumbnail" src="images/book1/ch13/screenshots/book1ch13_01.png" alt="book1ch13img1"></img>
        <img className="img-fluid img-thumbnail" src="images/book1/ch13/screenshots/book1ch13_02.png" alt="book1ch13img2"></img>
        <img className="img-fluid img-thumbnail" src="images/book1/ch13/screenshots/book1ch13_03.png" alt="book1ch13img3"></img>
        <img className="img-fluid img-thumbnail" src="images/book1/ch13/screenshots/book1ch13_04.png" alt="book1ch13img4"></img>
        <img className="img-fluid img-thumbnail" src="images/book1/ch13/screenshots/book1ch13_05.png" alt="book1ch13img5"></img>
        <img className="img-fluid img-thumbnail" src="images/book1/ch13/screenshots/book1ch13_06.png" alt="book1ch13img6"></img>
        <Row>
          <Col><Link to="/book1ch13" className="content-links"><h5>Back to Chapter 13</h5></Link></Col>
        </Row>
      </Container>
    </div>
  );
}
export default Book1Ch13Schillinger;